spring.application.name=task-manager-BackEnd

# CONFIGURATION GROQ (SPRING AI)
# ----------------------------------------------------
# Endpoint local d'Ollama (aucun apikey requis)
#spring.ai.ollama.base-url=http://localhost:11434
#Modèle installé sur ta machine
#spring.ai.ollama.chat.options.model=llama3.2

#spring.ai.openai.api-key=lm-studio
#spring.ai.openai.base-url=http://localhost:1234
#spring.ai.openai.chat.options.model=local-model


spring.ai.openai.base-url=https://api.groq.com
spring.ai.openai.api-key= tu_clave_aqui
spring.ai.openai.chat.options.model=llama-3.1-8b-instant
spring.ai.openai.chat.options.temperature=0.3
spring.ai.retry.max-attempts=2
spring.ai.retry.back-off.initial-interval=1000ms


# ----------------------------------------------------
# CONFIGURATION DE LA BASE DE DONNÉES (MySQL)
# ----------------------------------------------------
spring.datasource.url=jdbc:mysql://localhost:3307/task_manager_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ----------------------------------------------------
# CONFIGURATION JPA / HIBERNATE
# ----------------------------------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ----------------------------------------------------
# CONFIGURATION FLYWAY
# ----------------------------------------------------
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
spring.flyway.repair-on-migrate=true

# ----------------------------------------------------
# CONFIGURATION JWT
# ----------------------------------------------------
jwt.expiration=86400000
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970